version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: contracts-postgres
    environment:
      POSTGRES_DB: contracts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: contracts-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/contracts
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/contracts
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
